### ISSUE TITLE
FATA[0000] chip init failed

### ISSUE THREAD

**Issue by uspass** [donothingloop/c2prog#2]
@donothingloop 
Hi,
Done all preparation steps.
c2prog reset
returns
INFO[0000] Chip ID: 37, Rev ID: 2, Second Chip ID: 37

c2prog info
returns
INFO[0000] Chip ID: 37, Rev ID: 2, Second Chip ID: 37

c2prog read --fw out.bin
returns
INFO[0000] Found chip                                              Chip ID:37
FATA[0000] chip init failed                                          error="read error:3"

Any ideeas?

Thanks,
us

**Comment by donothingloop** [comment]
Could you please check if there are any errors in your kernel log by running the command 'dmesg'? Do this right after you try the c2prog read.

It looks like there might be something wrong with the c2prog kernel module.

**Comment by uspass** [comment]
@donothingloop 

Sorry, been out.
 Here is the log

pi@rpi:~ $ sudo modprobe c2prog c2d=23 c2ck=24
pi@rpi:~ $ sudo /home/pi/go/bin/c2prog info
INFO[0000] Chip ID: 37, Rev ID: 2, Second Chip ID: 37   
pi@rpi:~ $ sudo /home/pi/go/bin/c2prog read --fw /home/pi/go/bin/out.bin
INFO[0000] Found chip                                    Chip ID=37
FATA[0000] chip init failed                              error="read error: 3"
pi@rpi:~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.79-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1159 SMP Sun Nov 4 17:50:20 GMT 2018
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 8 MiB at 0x3ac00000
[    0.000000] On node 0 totalpages: 242688
[    0.000000] free_area_init_node: node 0, pgdat 80c85280, node_mem_map ba39f000
[    0.000000]   Normal zone: 2133 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 242688 pages, LIFO batch:31
[    0.000000] percpu: Embedded 17 pages/cpu @ba348000 s38720 r8192 d22720 u69632
[    0.000000] pcpu-alloc: s38720 r8192 d22720 u69632 alloc=17*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 240555
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1920 bcm2708_fb.fbheight=1080 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=368aadcb-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 940232K/970752K available (7168K kernel code, 576K rwdata, 2076K rodata, 1024K init, 698K bss, 22328K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
                   lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x80008000 - 0x80800000   (8160 kB)
                     .init : 0x80b00000 - 0x80c00000   (1024 kB)
                     .data : 0x80c00000 - 0x80c9017c   ( 577 kB)
                      .bss : 0x80c97f04 - 0x80d468b0   ( 699 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 25287 entries in 75 pages
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000019] Switching to timer-based delay loop, resolution 52ns
[    0.000267] Console: colour dummy device 80x30
[    0.000284] console [tty1] enabled
[    0.000309] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000324] pid_max: default: 32768 minimum: 301
[    0.000644] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000659] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001593] Disabling memory control group subsystem
[    0.001669] CPU: Testing write buffer coherency: ok
[    0.002085] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.002484] Setting up static identity map for 0x100000 - 0x10003c
[    0.002606] Hierarchical SRCU implementation.
[    0.003280] smp: Bringing up secondary CPUs ...
[    0.004052] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.004888] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.005707] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.005813] smp: Brought up 1 node, 4 CPUs
[    0.005824] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.005829] CPU: All CPU(s) started in HYP mode.
[    0.005833] CPU: Virtualization extensions available.
[    0.006754] devtmpfs: initialized
[    0.017012] random: get_random_u32 called from bucket_table_alloc+0xfc/0x24c with crng_init=0
[    0.017781] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.018002] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.018020] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.018576] pinctrl core: initialized pinctrl subsystem
[    0.019319] NET: Registered protocol family 16
[    0.022064] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.026945] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.026953] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.027155] Serial: AMBA PL011 UART driver
[    0.028820] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.029275] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.060821] bcm2835-dma 3f007000.dma: DMA legacy API manager at bb813000, dmachans=0x1
[    0.062237] SCSI subsystem initialized
[    0.062462] usbcore: registered new interface driver usbfs
[    0.062513] usbcore: registered new interface driver hub
[    0.062599] usbcore: registered new device driver usb
[    0.070085] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-11-04 16:31
[    0.071479] clocksource: Switched to clocksource arch_sys_counter
[    0.148537] VFS: Disk quotas dquot_6.6.0
[    0.148624] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.148808] FS-Cache: Loaded
[    0.149007] CacheFiles: Loaded
[    0.157827] NET: Registered protocol family 2
[    0.158545] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.158654] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.158840] TCP: Hash tables configured (established 8192 bind 8192)
[    0.158969] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.159013] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.159241] NET: Registered protocol family 1
[    0.159693] RPC: Registered named UNIX socket transport module.
[    0.159699] RPC: Registered udp transport module.
[    0.159704] RPC: Registered tcp transport module.
[    0.159710] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.161295] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.164038] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.172025] FS-Cache: Netfs 'nfs' registered for caching
[    0.172620] NFS: Registering the id_resolver key type
[    0.172650] Key type id_resolver registered
[    0.172656] Key type id_legacy registered
[    0.172671] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.174585] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.174713] io scheduler noop registered
[    0.174720] io scheduler deadline registered (default)
[    0.174887] io scheduler cfq registered
[    0.174895] io scheduler mq-deadline registered
[    0.174901] io scheduler kyber registered
[    0.177186] BCM2708FB: allocated DMA memory fad00000
[    0.177213] BCM2708FB: allocated DMA channel 0 @ bb813000
[    0.235260] Console: switching to colour frame buffer device 240x67
[    0.271171] bcm2835-rng 3f104000.rng: hwrng registered
[    0.271300] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.271826] vc-sm: Videocore shared memory driver
[    0.272104] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.281777] brd: module loaded
[    0.290781] loop: module loaded
[    0.290796] Loading iSCSI transport class v2.0-870.
[    0.291547] libphy: Fixed MDIO Bus: probed
[    0.291651] usbcore: registered new interface driver lan78xx
[    0.291711] usbcore: registered new interface driver smsc95xx
[    0.291727] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.317214] dwc_otg 3f980000.usb: base=0xf0980000
[    0.517457] Core Release: 2.80a
[    0.517466] Setting default values for core params
[    0.517501] Finished setting default values for core params
[    0.717756] Using Buffer DMA mode
[    0.717762] Periodic Transfer Interrupt Enhancement - disabled
[    0.717768] Multiprocessor Interrupt Enhancement - disabled
[    0.717775] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.717786] Dedicated Tx FIFOs mode
[    0.718151] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0xbad14000 dma = 0xfad14000 len=9024
[    0.718177] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.718184] dwc_otg: Microframe scheduler enabled
[    0.718241] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x805ea470
[    0.718253] WARN::hcd_init_fiq:460: FIQ ASM at 0x805ea7d8 length 36
[    0.718266] WARN::hcd_init_fiq:486: MPHI regs_base at 0xf0006000
[    0.718321] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.718357] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.718387] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.718436] Init: Port Power? op_state=1
[    0.718441] Init: Power Port (0)
[    0.718644] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.718656] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.718665] usb usb1: Product: DWC OTG Controller
[    0.718673] usb usb1: Manufacturer: Linux 4.14.79-v7+ dwc_otg_hcd
[    0.718681] usb usb1: SerialNumber: 3f980000.usb
[    0.719305] hub 1-0:1.0: USB hub found
[    0.719345] hub 1-0:1.0: 1 port detected
[    0.719890] dwc_otg: FIQ enabled
[    0.719895] dwc_otg: NAK holdoff enabled
[    0.719901] dwc_otg: FIQ split-transaction FSM enabled
[    0.719910] Module dwc_common_port init
[    0.720161] usbcore: registered new interface driver usb-storage
[    0.720331] mousedev: PS/2 mouse device common for all mice
[    0.720408] IR NEC protocol handler initialized
[    0.720414] IR RC5(x/sz) protocol handler initialized
[    0.720420] IR RC6 protocol handler initialized
[    0.720425] IR JVC protocol handler initialized
[    0.720429] IR Sony protocol handler initialized
[    0.720436] IR SANYO protocol handler initialized
[    0.720441] IR Sharp protocol handler initialized
[    0.720446] IR MCE Keyboard/mouse protocol handler initialized
[    0.720451] IR XMP protocol handler initialized
[    0.721147] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.721405] bcm2835-cpufreq: min=600000 max=1400000
[    0.721795] sdhci: Secure Digital Host Controller Interface driver
[    0.721800] sdhci: Copyright(c) Pierre Ossman
[    0.722161] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.722488] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.722580] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.724022] ledtrig-cpu: registered to indicate activity on CPUs
[    0.724171] hidraw: raw HID events driver (C) Jiri Kosina
[    0.724336] usbcore: registered new interface driver usbhid
[    0.724341] usbhid: USB HID core driver
[    0.724984] vchiq: vchiq_init_state: slot_zero = bad80000, is_master = 0
[    0.726542] [vc_sm_connected_init]: start
[    0.736372] [vc_sm_connected_init]: end - returning 0
[    0.736965] Initializing XFRM netlink socket
[    0.736990] NET: Registered protocol family 17
[    0.737108] Key type dns_resolver registered
[    0.737644] Registering SWP/SWPB emulation handler
[    0.738239] registered taskstats version 1
[    0.744598] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.744675] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    0.746554] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.746563] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    0.802134] sdhost: log_buf @ bad13000 (fad13000)
[    0.839944] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.841518] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.843063] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.845838] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.881500] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.882566] of_cfs_init
[    0.882653] of_cfs_init: OK
[    0.883253] Waiting for root device PARTUUID=368aadcb-02...
[    0.921386] random: fast init done
[    0.929342] mmc1: new high speed SDIO card at address 0001
[    0.931595] Indeed it is in host mode hprt0 = 00021501
[    1.141585] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.141698] Indeed it is in host mode hprt0 = 00001101
[    1.381716] usb 1-1: New USB device found, idVendor=0424, idProduct=2514
[    1.381727] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.382300] hub 1-1:1.0: USB hub found
[    1.382376] hub 1-1:1.0: 4 ports detected
[    1.701504] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.831709] usb 1-1.1: New USB device found, idVendor=0424, idProduct=2514
[    1.831720] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.832200] hub 1-1.1:1.0: USB hub found
[    1.832279] hub 1-1.1:1.0: 3 ports detected
[    1.931505] usb 1-1.2: new full-speed USB device number 4 using dwc_otg
[    2.077440] usb 1-1.2: New USB device found, idVendor=046d, idProduct=c52b
[    2.077452] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.077460] usb 1-1.2: Product: USB Receiver
[    2.077468] usb 1-1.2: Manufacturer: Logitech
[    2.161510] usb 1-1.1.3: new high-speed USB device number 5 using dwc_otg
[    2.292364] usb 1-1.1.3: New USB device found, idVendor=0781, idProduct=5583
[    2.292375] usb 1-1.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.292384] usb 1-1.1.3: Product: Ultra Fit
[    2.292392] usb 1-1.1.3: Manufacturer: SanDisk
[    2.292400] usb 1-1.1.3: SerialNumber: 4C530001291022122565
[    2.293006] usb-storage 1-1.1.3:1.0: USB Mass Storage device detected
[    2.293534] scsi host0: usb-storage 1-1.1.3:1.0
[    2.391587] usb 1-1.3: new full-speed USB device number 6 using dwc_otg
[    2.526816] usb 1-1.3: New USB device found, idVendor=046d, idProduct=c52b
[    2.526827] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.526836] usb 1-1.3: Product: USB Receiver
[    2.526844] usb 1-1.3: Manufacturer: Logitech
[    2.621517] usb 1-1.1.1: new high-speed USB device number 7 using dwc_otg
[    2.771970] usb 1-1.1.1: New USB device found, idVendor=0424, idProduct=7800
[    2.771981] usb 1-1.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.039822] libphy: lan78xx-mdiobus: probed
[    3.352371] scsi 0:0:0:0: Direct-Access     SanDisk  Ultra Fit        1.00 PQ: 0 ANSI: 6
[    3.353560] sd 0:0:0:0: [sda] 120127488 512-byte logical blocks: (61.5 GB/57.3 GiB)
[    3.354391] sd 0:0:0:0: [sda] Write Protect is off
[    3.354404] sd 0:0:0:0: [sda] Mode Sense: 43 00 00 00
[    3.354729] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[    3.365343]  sda: sda1 sda2
[    3.367611] sd 0:0:0:0: [sda] Attached SCSI removable disk
[    3.411562] EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts: (null)
[    3.411623] VFS: Mounted root (ext4 filesystem) readonly on device 8:2.
[    3.424337] devtmpfs: mounted
[    3.427733] Freeing unused kernel memory: 1024K
[    3.846425] systemd[1]: System time before build time, advancing clock.
[    3.992734] NET: Registered protocol family 10
[    4.012273] Segment Routing with IPv6
[    4.021878] ip_tables: (C) 2000-2006 Netfilter Core Team
[    4.040208] random: systemd: uninitialized urandom read (16 bytes read)
[    4.046171] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    4.046747] systemd[1]: Detected architecture arm.
[    4.048159] systemd[1]: Set hostname to <rpi>.
[    4.085029] random: systemd: uninitialized urandom read (16 bytes read)
[    4.150961] random: systemd-cryptse: uninitialized urandom read (16 bytes read)
[    4.690333] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    4.690806] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    4.691090] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[    4.691560] systemd[1]: Listening on Journal Socket.
[    4.692367] systemd[1]: Created slice System Slice.
[    4.697030] systemd[1]: Starting Set the console keyboard layout...
[    4.698348] systemd[1]: Created slice system-systemd\x2dfsck.slice.
[    4.831846] i2c /dev entries driver
[    5.433652] random: crng init done
[    5.433667] random: 7 urandom warning(s) missed due to ratelimiting
[    5.433711] EXT4-fs (sda2): re-mounted. Opts: (null)
[    5.511386] systemd-journald[96]: Received request to flush runtime journal from PID 1
[    6.077997] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[    6.082282] bcm2835_alsa bcm2835_alsa: card created with 8 channels
[    6.237711] logitech-djreceiver 0003:046D:C52B.0003: hiddev96,hidraw0: USB HID v1.11 Device [Logitech USB Receiver] on usb-3f980000.usb-1.2/input2
[    6.272037] brcmfmac: F1 signature read @0x18000000=0x15264345
[    6.281104] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43455-sdio.bin for chip 0x004345(17221) rev 0x000006
[    6.282311] usbcore: registered new interface driver brcmfmac
[    6.341916] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    6.373479] logitech-djreceiver 0003:046D:C52B.0006: hiddev97,hidraw1: USB HID v1.11 Device [Logitech USB Receiver] on usb-3f980000.usb-1.3/input2
[    6.565932] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
[    6.566677] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 9.10.105 Compiler: 1.29.4 ClmImport: 1.36.3 Creation: 2018-03-09 18:56:28 
[    6.611813] input: Logitech K230 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.2/0003:046D:C52B.0003/0003:046D:400D.0007/input/input0
[    6.613794] logitech-hidpp-device 0003:046D:400D.0007: input,hidraw2: USB HID v1.11 Keyboard [Logitech K230] on usb-3f980000.usb-1.2:2
[    6.627185] input: Logitech M525 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.2/0003:046D:C52B.0006/0003:046D:4013.0008/input/input1
[    6.627621] logitech-hidpp-device 0003:046D:4013.0008: input,hidraw3: USB HID v1.11 Mouse [Logitech M525] on usb-3f980000.usb-1.3:1
[    7.968247] uart-pl011 3f201000.serial: no DMA platform data
[    8.820392] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    8.820450] brcmfmac: power management disabled
[    9.118431] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    9.129334] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    9.611975] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k FS
[   14.976732] fuse init (API version 7.26)
[   15.029445] Bluetooth: Core ver 2.22
[   15.029505] NET: Registered protocol family 31
[   15.029508] Bluetooth: HCI device and connection manager initialized
[   15.029531] Bluetooth: HCI socket layer initialized
[   15.029539] Bluetooth: L2CAP socket layer initialized
[   15.029562] Bluetooth: SCO socket layer initialized
[   15.088147] Bluetooth: HCI UART driver ver 2.3
[   15.088160] Bluetooth: HCI UART protocol H4 registered
[   15.088163] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   15.088311] Bluetooth: HCI UART protocol Broadcom registered
[   15.517344] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   15.517350] Bluetooth: BNEP filters: protocol multicast
[   15.517362] Bluetooth: BNEP socket layer initialized
[   15.604130] Bluetooth: RFCOMM TTY layer initialized
[   15.604183] Bluetooth: RFCOMM socket layer initialized
[   15.604200] Bluetooth: RFCOMM ver 1.11
[   39.236305] logitech-hidpp-device 0003:046D:4013.0008: HID++ 2.0 device connected.
[   54.948346] logitech-hidpp-device 0003:046D:400D.0007: HID++ 2.0 device connected.
[   84.228560] c2prog: loading out-of-tree module taints kernel.
[   84.229420] Registering c2prog module.
[   84.229685] c2prog: registered character device
pi@rpi:~ $

**Comment by uspass** [comment]
I forgot to tell you.
I had to change the makefile for kernel to:
c2prog-objs := c2_interface.o c2prog_dev.o
obj-m += c2prog.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd) clean
install:
	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd) modules_install

I couldn't get make working with M=$(PWD)
I don't know much about Linux, so please, bear with me.

Thanks,
us

**Comment by uspass** [comment]
Started from the scratch with kernel.
That is deleted c2prog.ko from /lib.
Deleted all object files.
Rebooted and checked if everything is OK.
From what I can tell dmesg looks good.
make #again original version (with M=$(PWD))
make install #original version
This time all looks good, no error. 
I have c2prog in /dev
But got the same problem in dmesg
.....
[ 3534.175011] c2prog: loading out-of-tree module taints kernel.
[ 3534.175886] Registering c2prog module.
[ 3534.176240] c2prog: registered character device

and:
c2prog info
INFO[0000] Chip ID: 37, Rev ID: 2, Second Chip ID: 37

c2prog read --fw out.bin
INFO[0000] Found chip Chip ID:37
FATA[0000] chip init failed error="read error:3"

Thanks, 
us

**Comment by donothingloop** [comment]
I've just pushed a new version of the utility that has some additional debug output in order to isolate the issue to the specific chip init step.

Could you please try again with the new version of the userspace tool?

**Comment by donothingloop** [comment]
Just pushed a second version that prints a more verbose error.
The error code that you are getting is directly from the EFM8SB1 and indicates a flash error.

My guess would be that you are either trying to read from a protected microcontroller or that there is something wrong with the power-supply circuit.

**Comment by uspass** [comment]
Might be a protected flash.
I don't think is power related.
The schematics are here:
https://github.com/uspass/Tuya-Water-Leak-Sensor/blob/master/Water%20Leak%20Sensor%20Schematics.pdf
It is battery powered.
I have removed D4 to cut off permanently the power of the esp8266 because I didn't want to have the EFM serial talking to ESP.

Thanks,
us
Oh. Inadvertently I powered off the pi and something went wrong. I get gui but no mouse and no kbd.
Ssh still works, though.
fsck shows dirty bit.
backup to original doesn't help.
Looks like I have to reinstall all again.

**Comment by uspass** [comment]
OK,
Done it from ssh.
chip init failed - flash timing

btw. did you check the apn 127 v1.2?
I'm asking because I've seen some posts saying that the v1.4 is wrong in some places.
I do have both. I'll upload on my repo.

**Comment by uspass** [comment]
@donothingloop 
Hi,

Any news?

Thanks,
us

**Comment by donothingloop** [comment]
Hi,
I'm fairly confident that your chip is flash readout locked.
Unfortunately i currently do not have the time to try this out by locking a blank EFM8SB1 chip, but when my assumption is true, the same error message should be thrown.

I did not find any information about the error codes of the C2 protocol, would be a big help if you find some.

**Comment by uspass** [comment]
@donothingloop 

Thank you for the answer.
I found this https://rebyte.me/en/silicon-labs/
It has tons of docs from Silicon Labs.
From what I have seen the docs are in alphabetical order.
Especially interesting is https://rebyte.me/en/silicon-labs/161718/ for EFM8SB10F2G-QFN20.

Cheers,
us
